version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_product_api
    restart: always
    environment:
      POSTGRES_DB: product-api      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root        
    ports:
      - "5436:5432"               
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
